name: test

on:
  push:
    branches: [main, master, staging, dev, feat/**, fix/**, y-monorepo]


jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test --summary -s -vvv
        env:
          MAINNET_RPC_URL: https://mainnet.gateway.tenderly.co
          OPTIMISM_RPC_URL: https://optimism.gateway.tenderly.co
          ARBITRUM_RPC_URL: https://arbitrum.gateway.tenderly.co
        id: test

  forge_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Node modules
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - name: Print coverage
        run: forge b; forge coverage
